data: sst2
batch_size: 32
optimizer: adam
epoch: 10
weight_decay: 0
lr: 2e-5
warmup_epochs: 3
orig_data_path: ../data/clean/sst-2
poison_data_path: ../data/poison/sst-2-all
output_data_path: ../data/poison/sst-2
save_path: ./models/hiddenkiller/poison_bert_sst2.pkl
target_label: 1
poison_rate: 10
