dataset: sst-2
data_dir: ../data/clean/sst-2
model: bert-base-uncased
batchsize: 32
poison_rate: 0.1
target_label: 1
model_save_path: ./models/lws
data_cache_path: ../data/clean/lws_cached
max_epoch_clean: 5
max_epoch_poison: 15
device: 0